layout_spectrum: 0.7986285945253981
typography_spectrum: 0.92514126749073
color:
  brandStrength: 0.9892785964387995
  lightness: 0.03289375771362666
  saturation: 0.4559149492057133
  rhythmicContrast: 0.4189198818642388
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
github: true
author:
  name: LG Larsen
  email: armilla420@gmail.com
  url: 'https://thegrid.ai/lg-larsen/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e8ca627-f068-4663-aef4-7e175a605f1e.jpg
name: LG Larsen
navigation:
  - name: Contact
    id: 09a989b3-ee6d-4fdd-b991-8f90c3a27b0d
    type: content
  - name: LG
    id: 00af74d4-e9b6-463e-a1b6-000e0cbd3989
    type: content
  - name: DeeMiiNovo
    id: ead92aee-60cf-44d6-aa7e-e5b76ab89e8e
    type: content
  - name: LGsamiCrafts
    url: 'https://thegrid.ai/lgsamicrafts/'
    type: external
  - name: LGsignD
    url: 'https://thegrid.ai/lgsignd/'
    type: external
  - name: LG´s Telescreen
    id: 40a9f386-cb40-4fd8-be05-7bed09bdd6b6
    type: content
  - name: Shops
    id: 26117ee8-33f8-4ccb-9c14-7e9d0a33fe35
    type: content
  - name: OurFriends
    url: 'https://thegrid.ai/ourfriends/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/736bbab0-cc32-40d0-8080-61b35f43d46d.jpg
title: Handicraft with Design
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fcc28aeb-0d54-4a80-80df-b5086ec070e8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fcc28aeb-0d54-4a80-80df-b5086ec070e8.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  "Silence is the Mother of all my creativity.  I´m only blessed to be her
  worker"     LG
purpose: []
